name: Publish Release

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
      - run: gpg --quiet --batch --yes --decrypt --passphrase="$PASS" --output=secring.gpg secring.gpg.gpg
        env:
          PASS: ${{ secrets.FREEFAIR_SECRING_PASS }}
      - name: Publish package
        run: ./gradlew --no-parallel publishToSonatype publishPlugins uploadDocs closeAndReleaseRepository -Psigning.secretKeyRingFile=$GITHUB_WORKSPACE/secring.gpg -Psigning.password=$SIGNING_PASSWORD -Psigning.keyId=$SIGNING_KEY_ID
        env:
          ORG_GRADLE_PROJECT_ossrhUser: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_ossrhPass: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.FREEFAIR_SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.FREEFAIR_SIGNING_PASSWORD }}
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
          ORG_GRADLE_PROJECT_freefairDocsUser: ${{ secrets.FREEFAIR_DOCS_USER }}
          ORG_GRADLE_PROJECT_freefairDocsPass: ${{ secrets.FREEFAIR_DOCS_PASS }}
